- README.md
More info about the project
User guideline
> Add more to readme

- server/.gitignore
- server/README.md
> init server config

- server/src/api/resources/user/user.model.js
> fix: missing document name

- client/src/App.js
- client/src/login.js
- client/src/signUp.js
- server/yarn.lock
Ran yarn with server engine dependencies - yarn lock might still be a merge conflict
> basic forms

- server/src/api/resources/user/user.controller.js
- server/src/config/index.js
- server/src/config/prod.js
- server/src/db.js
- Update `baseConfig` and `prod.config`
- Fix bug in `getOneUser` where the wrong user would be returned
- Remove the `findOne` wrapper in `updateUser`. Simply using `findOneAndUpdate` will suffice
- Return the newly updated user instead of old in `updateUser`
- Swap out deprecated function in `deleteUser` with `findOneAndDelete`
- Pass `useFindAndModify` option to `mongoose.connect` to remove other deprecation warnings
> Update config files with JWT_SECRET env variable

- server/src/api/resources/trip/trip.model.js
- server/src/api/resources/trip/trip.restRouter.js
- server/src/api/restRouter.js
This fixes:
- Typos in trip.model.js: 1. require instead of required; 2. ISOdate instead of Date; 3. decimal instead of Number
- Export trip router from trip.restRouter.js
- Mount trip router at /api/trips
@alexbotello if you see anything that needs to change please let me know!
> [Server] Trip resource fix

- .travis.yml
- scripts/test
- server/package.json
- server/src/api/resources/user/user.model.js
- server/src/config/prod.js
- server/src/config/testing.js
- server/src/db.js
- server/src/server.js
- server/tests/setup.js
- server/tests/tests/testUser.js
- server/yarn.lock
- Jest is now successfully integrated with travis-ci
- Adds basic tests for User model and endpoints
---
In order to protect sensitive information from being exposed to unauthorized users, Travis CI does **_not_** expose it's set environment variables to forks of the master repo. This prevents any nefarious individuals from simply running a build, console logging the env variables and then stealing them.
Moving forward this means all branching and workflow must be done on the master repository. Any work submitted from your own forked repo will **FAIL** the intergration tests. Please make sure to adjust your workflow accordingly.
> Add tests for User endpoints

- server/src/api/resources/waypoint/waypoint.controller.js
- server/src/api/resources/waypoint/waypoint.model.js
- server/src/api/resources/waypoint/waypoint.restRouter.js
- server/src/api/restRouter.js
- server/tests/modules/testWaypoint.js
Waypoint model and endpoints have been added.
Endpoints now available:
- Get all waypoints in database - `/api/waypoints/`
- Create a new waypoint - `/api/waypoints/`
- Get a single waypoint - `/api/waypoints/:id`
- Update a single waypoint - `/api/waypoints/:id`
- Delete a single waypoint - `/api/waypoints/:id`
- Get all waypoints for a trip - `/api/waypoints/trip/:tripId`
- Delete all waypoints for a trip - `/api/waypoints/trip/:tripId`
I will update API documentation in my next PR
> Add Waypoint controller and endpoints

- docs/Trip.md
- server/tests/mock.js
- server/tests/modules/testTrip.js
- server/tests/modules/testUser.js
- server/tests/modules/testWaypoint.js
- server/tests/setup.js
- Adds tests for `Trip` model and endpoints
> Add tests for Trip endpoints

- client/.gitignore
Add client/.env to .gitignore so nobody learns our secrets
> add .env to client/.gitignore (1 line)

- client/package.json
- client/src/components/AppContainer.js
- client/src/components/Billing.js
- client/src/redux/actions/auth.js
- client/src/redux/actions/billing.js
- client/src/redux/actions/trips.js
- client/src/redux/reducers/billing.js
- server/src/api/resources/subscribe/subscribe.controller.js
- To replace `console.log(error)`
- To display meaningful error message to user
- Fix some error caughts in requests
> Add Toast notification

- client/src/components/Maps/createTrip/createTripPanel.js
- client/src/components/Maps/createTrip/custom.css
- client/yarn.lock
> Create trip ux

- client/src/components/forms/CheckoutForm.js
- client/src/components/forms/SettingsForm.js
- client/src/styles/Billing.styles.js
- client/src/styles/CheckoutForm.styles.js
- client/src/styles/Settings.styles.js
PR for responsive design for the billing and settings component. 
> [Client] Responsive design for settings and billing component

- client/src/components/DashboardHome.js
- client/src/components/Maps/singleTrip/index.js
- client/src/styles/Sidebar.styles.js
- client/src/styles/TripCard.styles.js
- client/src/styles/theme/variables.js
- add shouldComponentUpdate to singleTrip
- add absolute position and z-index to sidebar
- add close modal button
- fix modal logic to close when user location is set
Fixes #99 and #98 
> [Bug fix] Map no longer re-renders when sidebar is toggled

- docs/Trip.md
- server/src/api/modules/public.js
- server/src/api/resources/trip/trip.model.js
- server/src/api/resources/trip/trip.restRouter.js
- server/src/api/restRouter.js
- server/tests/mock.js
- server/tests/modules/testPublic.js
- server/tests/modules/testTrip.js
- server/tests/modules/testUser.js
- server/tests/setup.js
- Add `/api/public/trips` endpoint
- Add `/api/public/trips/:id` endpoint
- Add `isPublic` property to `Trip` model. Defaults to false
- Add tests for both endpoints
- Add documentation to reflect changes
> Add public trip endpoints on the backend

- client/src/components/Trips.js
Fixes render logic for trip list
> fix render logic for trip list

- client/src/components/Maps/singleTrip/activePanel.js
- client/src/components/Maps/singleTrip/mapUtil.js
- client/src/components/Maps/singleTrip/tripPanel.js
- client/src/components/Maps/singleTripPublic/mapUtil.js
Calculate time gap between waypoints
> Calculate time gap between waypoints

- client/src/components/TripCard.js
- client/src/components/Trips.js
- client/src/styles/TripCard.styles.js
- Change `Archive` and `Share` buttons to be secondary color
- Remove circle/chevron button on `TripCard`
- Wrap `TripCard` with a `Link` component to make entire card a link button
> Update TripCard CSS/UI

- client/src/components/Billing/PaymentDetails.js
- client/src/components/Billing/Plans.js
- client/src/components/LandingNav.js
> Change plan price and remove date

- client/src/components/TripCard.js
- client/src/components/Trips.js
@ahrjarrett I tried using `z-index` in the css, which did manage to get the buttons properly working, except the `Link` component would still also fire.
The quick fix I found was simply just wrapping the card image with the `Link` component instead.
> [Bug Fix] - TripCard Link and buttons now properly work

- client/src/components/Maps/singleTrip/Progress.js
- client/src/components/Maps/singleTrip/activePanel.js
- client/src/components/Maps/singleTrip/index.js
- client/src/components/Root.js
Update to single trip view and active trip views
> Active trip views

- client/src/components/AppContainer.js
- client/src/components/AuthenticatedLinks.js
- client/src/components/DashboardHome.js
- client/src/components/Dropdown.js
- client/src/components/EditTrip.js
- client/src/components/LandingPage/Header.js
- client/src/components/Maps/singleTrip/activePanel.js
- client/src/components/Maps/singleTrip/index.js
- client/src/components/Maps/singleTrip/tripPanel.js
- client/src/components/Maps/singleTripPublic/activePanel.js
- client/src/components/Maps/singleTripPublic/index.js
- client/src/components/Maps/singleTripPublic/mapUtil.js
- client/src/components/NewTrip.js
- client/src/components/PublicTripCard.js
- client/src/components/Sidebar.js
- client/src/components/TripPictures.js
- client/src/components/forms/SettingsForm.js
- client/src/components/forms/UpdatePassword.js
- client/src/redux/actions/auth.js
- client/src/redux/actions/billing.js
- client/src/redux/actions/trips.js
- client/src/store.js
- server/src/config/index.js
- server/tests/modules/testTwilio.js
removed invoice from dropdown, added logout. Removed commented code. 
> UI fix/ removed commented code

- client/src/components/Maps/singleTrip/tripPanel.js
- client/src/redux/actions/settings.js
- Missing authorization header for onboard
> Missing authorization header for onboard

- README.md
Update `README.md` to include D3 information.
> Update Documentation on D3

- README.md
> Update README to set up firebase and stripe

- client/src/components/Maps/SingleTrip/TripPanel.js
I forgot to update mobile button event in #150. This is the fix for that.
> [Bug Fix] Mobile start trip button now works

- README.md
> Instruction to set up Cloudinary integration

- client/public/index.html
- client/src/components/PublicTripCard.js
- client/src/components/TripCard.js
- client/src/config/firebase.js
- client/src/config/index.js
Added `REACT_APP_MAPS_KEY` to `.env.development`
> Move Google Maps API Key to environment variable
